from typing import Literal

Info_Statuses = Literal[
    "ALL",
    "VISIBLE",
    "INVISIBLE",
    "EMPTY_STOCK",
    "NOT_MODERATED",
    "MODERATED",
    "DISABLED",
    "STATE_FAILED",
    "READY_TO_SUPPLY",
    "VALIDATION_STATE_PENDING",
    "VALIDATION_STATE_FAIL",
    "VALIDATION_STATE_SUCCESS",
    "TO_SUPPLY",
    "IN_SALE",
    "REMOVED_FROM_SALE",
    "BANNED",
    "OVERPRICED",
    "CRITICALLY_OVERPRICED",
    "EMPTY_BARCODE",
    "BARCODE_EXISTS",
    "QUARANTINE",
    "ARCHIVED",
    "OVERPRICED_WITH_STOCK",
    "PARTIAL_APPROVED",
    "IMAGE_ABSENT",
    "MODERATION_BLOCK",
]

Currency_Codes = Literal[
    "RUB",
    "BYN",
    "KZT",
    "EUR",
    "USD",
    "CNY",
]

Posting_Statuses = Literal[
    "acceptance_in_progress",
    "awaiting_approve",
    "awaiting_packaging",
    "awaiting_registration",
    "awaiting_deliver",
    "arbitration",
    "client_arbitration",
    "delivering",
    "driver_pickup",
    "not_accepted",
    "sent_by_seller",
    "cancelled_from_split_pending",
    "cancelled",
    "awaiting_verification",
]

Posting_SubStatuses = Literal[
    "posting_acceptance_in_progress",
    "posting_in_arbitration",
    "posting_created",
    "posting_in_carriage",
    "posting_not_in_carriage",
    "posting_registered",
    "posting_transferring_to_delivery",
    "posting_awaiting_passport_data",
    "posting_created",
    "posting_awaiting_registration",
    "posting_registration_error",
    "posting_transferring_to_delivery",
    "posting_split_pending",
    "posting_canceled",
    "posting_in_client_arbitration",
    "posting_delivered",
    "posting_received",
    "posting_conditionally_delivered",
    "posting_in_courier_service",
    "posting_in_pickup_point",
    "posting_on_way_to_city",
    "posting_on_way_to_pickup_point",
    "posting_returned_to_warehouse",
    "posting_transferred_to_courier_service",
    "posting_driver_pick_up",
    "posting_not_in_sort_center",
    "sent_by_seller",
]
